services:
  nuxt-app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NUXT_PORT=8080
    volumes:
      - ./src:/app/src
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge
